sudo: false
language: node_js
node_js:
  - 8
  - 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn test

after_success: 
  - |
    npm install --save-dev coveralls@2.10.0
    npx nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js
